apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-gw
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - nginx.tmanet.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - nginx.tmanet.com
    tls:
      credentialName: gw-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
spec:
  hosts:
  - nginx.tmanet.com
  gateways:
  - nginx-gw
  http:
  - route:
    - destination:
        host: nginx
        port:
          number: 443